// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1J0xUHNWcV-n0uxQX4bo-qDjLKUhYIf0',
    appId: '1:545450534181:web:48de236f971459ab11e6cc',
    messagingSenderId: '545450534181',
    projectId: 'au-fix',
    authDomain: 'au-fix.firebaseapp.com',
    storageBucket: 'au-fix.appspot.com',
    measurementId: 'G-FTCDMTMZ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAci5u0q_rKcG8kVrDPXPAiqiATEWfqQcE',
    appId: '1:545450534181:android:09583dc8b7d1f51611e6cc',
    messagingSenderId: '545450534181',
    projectId: 'au-fix',
    storageBucket: 'au-fix.appspot.com',
  );
}
